version: '3'
services:
  api:
    #restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 5460
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - '0.0.0.0:5460:5460'
    expose:
      - '5460'

